### ISSUE TITLE
docker-compose Failed

### ISSUE THREAD

**Issue by katepangLiu** [DataDog/dd-trace-httpd#1]
```shell
cd dd-trace-httpd
docker-compose up
```

Cloning into 'dd-opentracing-cpp'...
**fatal: Remote branch cgilmour/pic not found in upstream origin**
The command '/bin/sh -c cd /var/tmp/localbuild && git clone -b cgilmour/pic https://github.com/DataDog/dd-opentracing-cpp && cd dd-opentracing-cpp && ./scripts/install_dependencies.sh && mkdir .build && cd .build && cmake -DBUILD_SHARED=Off -DBUILD_STATIC=On .. && make && make install' returned a non-zero code: 128
ERROR: Service 'traced-httpd-ubuntu1804' failed to build : Build failed

**Comment by cgilmour** [comment]
Hi @katepangLiu thanks for reporting this!
This was published while still using a specific branch of another project we maintain. The PR for that specific change got merged and the branch was automatically deleted. That caused the builds to be broken.

I've changed it now for the ubuntu and centos 8 builds in #2, but not for centos 6 because of reasons explained in that PR. After that is merged, you should be able to update and run `docker-compose` up successfully

**Comment by katepangLiu** [comment]
Good Job, It Work.
